spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/?retryWrites=true&w=majority&appName=kitchensink
      database: ${MONGO_DATABASE}
      auto-index-creation: true

  thymeleaf:
    mode: HTML
    suffix: .html


logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret:
    key: your_secret_key_your_secret_key_your_secret_key_1234 # Replace with a generated key in prod
  token:
    expiration: 3600000 # Expiration time in milliseconds (15 minutes)