spring:
  data:
    mongodb:
      uri: mongodb+srv://heygauravjain:gaurav124@cluster0.ynujrdv.mongodb.net/
      database: kitchensink
      auto-index-creation: true

  thymeleaf:
    mode: HTML
    suffix: .html

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        
jwt:
  secret:
    key: Srgl71VAmMhSVI+8Bb5eQB6HFr3HdUbidBb/xoTWZAM= # Replace with a generated key in prod
  access:
    token:
      expiration: 900000 # 15 minutes in milliseconds
  refresh:
    token:
      expiration: 604800000 # 7 days in milliseconds